node ('Slave'){

  stage('checkout') {
      
        git credentialsId: '', url: 'https://github.com/ZiyaadQasem/top-spring-boot-docker.git'
    }
  
  stage("build"){
            sh "mvn clean verify f /demo/pom.xml"
    }
    
    stage("two"){
            sleep 10
            echo 'hello from stage 2'
        }
}
