node ('Slave'){

  stage('checkout') {
      
        git credentialsId: '', url: 'https://github.com/ZiyaadQasem/top-spring-boot-docker.git'
    }
  
  stage("test-build"){
            sh "mvn clean install -f ./demo/pom.xml"
    }
    
    stage("build image"){
            sh 'docker build -t salla-demo -f ./demo/Dockerfile'
            echo 'hello from stage 2'
        }
}
